### ISSUE TITLE
sandbox.listWebtask should allow for lack of options

### ISSUE THREAD

**Issue by tjanczuk** [auth0/sandboxjs#10]
I need to specify `{}` for options even if I don't care to customize any.

**Comment by rwtombaugh** [comment]
good question

**Comment by NotMyself** [comment]
Hi @tjanczuk,

It looks like the [method](https://github.com/auth0/sandboxjs/blame/fa06fb61b65ac44dc4651bcfba4a7a1e2b4a1c7c/lib/sandbox.js#L601) now defaults to not requiring an empty object.
