### ISSUE TITLE
ctx.user is undefined

### ISSUE THREAD

**Issue by vincentlaucy** [auth0/sandboxjs#11]
Hi there, I am making use of `ctx.user` at my webtask code. Meanwhile seems it's empty when executed with sandboxjs and there is no way to inject such param. Is it make sense to have that included or are there any workaround?

**Comment by NotMyself** [comment]
Hi @vincentlaucy,

Sorry for the very late response to this issue. I am attempting to get us caught up and responding to all of our old tickets. This one is close to two years old. I am going to close it. If you are still having this issue, please feel free to respond and reopen it.

Thanks for using webtask!
