### ISSUE TITLE
Feedback from the documentation and general usage of the API

### ISSUE THREAD

**Issue by alejofernandez** [auth0/sandboxjs#2]
First of all, this is all minor feedback/suggestions, I've managed to integrate this library into my workflow and publish a webtask in minutes, with the given documentation and really short experience using `wt-cli`.
- It would be nice to document the `options` object, specially for `#create` or `#run`, probably anyone with minimal experience using webtasks would be able to infer all params, but I believe it adds value to have it documented.

<img width="550" alt="screen shot 2015-11-28 at 9 07 21 pm" src="https://cloud.githubusercontent.com/assets/1288192/11454688/cfe0a392-9614-11e5-81c9-ac3306cd74cc.png">
- On the same note, I would also expect the options object to accept API param names, like `ectx`, `pctx`, `pb`, `mb`, that would make a thin layer on top of the API, unless there are plans to change the API contract.
- From the following code sample it is a bit confusing that the token is retrieved from `process.env.WEBTASK_TOKEN`, at first I thought that `wt-cli` stored the default token in an environment variable, then I found that it didn't. Instead I would put something like `'{your webtask token goes here}'` and add a small documentation describing how to get a webtask token (that's the approach I took in my repo https://github.com/AlejoFernandez/webtask-api-boilerplate/blob/master/working-with-webtasks.md)

<img width="550" alt="screen shot 2015-11-28 at 9 07 45 pm" src="https://cloud.githubusercontent.com/assets/1288192/11454692/ecfaba94-9614-11e5-934f-c648ac8a1ed0.png">

That's pretty much it, but I just have a question, any plans for `wt-cli` to use `sandboxjs` to communicate with the API, saw a lot of code that looks similar in both repos :-)

I really like the concept of webtasks, I believe that it opens a lot of possibilities for developers. Please keep up the good work!

Cheers,
Alejo.

**Comment by NotMyself** [comment]
Hi @alejofernandez,

Thanks for the feedback. I have passed the feedback along to our docs team for consideration during future revisions.
